postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  url: <%= Rails.application.secrets.database_uri %>

test:
  <<: *postgres
  database: scarif_test
  username:
  password:

