postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *postgres
  url: <%= Rails.application.secrets.database_uri %>

test:
  <<: *postgres
  url: <%= Rails.application.secrets.database_uri %>

