# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60735d1e72a440faa9e4e62a36dda35df4afc5a46a5bd1e2bc99a0cb3e878eed40b7f441bb954a48f9fa8228d261b220a79b5a74da3b5e26f8533a6e65c6163c
  database_uri: postgres://localhost:5432/used_towels_development
  mailer_address: ''
  mailer_domain: ''
  mailer_password: ''
  mailer_username: ''

test:
  secret_key_base: 4bf26bcb39c4ba35b0dcee9bc252f4fb423fc2315595418664106f92f2f23a9a4dab9f1ee4883084dcad5f00027ed9b2cdf30706c04cd1c4f582c966632f1227
  database_uri: postgres://localhost:5432/used_towels_test
  mailer_address: ''
  mailer_domain: ''
  mailer_password: ''
  mailer_username: ''

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_uri: postgres://localhost:5432/used_towels_production
  mailer_address: ''
  mailer_domain: ''
  mailer_password: ''
  mailer_username: ''